### ISSUE TITLE
Options dont work Interacr Connetions etc but Close all connect and List work

### ISSUE THREAD

**Issue by KrystekYT** [xp4xbox/Python-Backdoor#55]
Options dont work but CLose connections and List work

**Comment by RushilKoul** [comment]
yes, only the list available connections/close connection/etc option works without adding an additional argument.
if you don't provide an argument on a command, it returns an error. in order to use the client, you will have to use an argument.


# EXAMPLE
**You launch the client and the server. The server.py displays a connection.**

You won't be able to use `I` to interact with the connection. you will have to specify which connection to interact with in the first place. Using `L` to list all connections gives the list of connections available. You'll see that the online connection list would only have one connection(in this scenario) and it's indexed at `0`

hence, you'll have to use `I 0` in order to access that connection. same goes for almost all the commands that don't work properly even if you type the command correctly. you'll most definitely have to add an argument.

You use `I 0` in the console. It connects to that pc and you get access to all the commands.
